# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: puzzlebot.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpuzzlebot.proto\x12\nRPCDemoPkg\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x08Odometry\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01\"\xba\x01\n\todometryM\x12\r\n\x05poseX\x18\x01 \x01(\x01\x12\r\n\x05poseY\x18\x02 \x01(\x01\x12\r\n\x05poseZ\x18\x03 \x01(\x01\x12\x14\n\x0corientationX\x18\x04 \x01(\x01\x12\x14\n\x0corientationY\x18\x05 \x01(\x01\x12\x14\n\x0corientationZ\x18\x06 \x01(\x01\x12\x14\n\x0corientationW\x18\x07 \x01(\x01\x12\x11\n\tLinXSpeed\x18\x08 \x01(\x01\x12\x15\n\rAngThetaSpeed\x18\t \x01(\x01\x32R\n\x11PuzzlebotOdometry\x12=\n\x0bGetOdometry\x12\x16.google.protobuf.Empty\x1a\x14.RPCDemoPkg.Odometry\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'puzzlebot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ODOMETRY'].fields_by_name['values']._options = None
  _globals['_ODOMETRY'].fields_by_name['values']._serialized_options = b'\020\001'
  _globals['_ODOMETRY']._serialized_start=60
  _globals['_ODOMETRY']._serialized_end=90
  _globals['_ODOMETRYM']._serialized_start=93
  _globals['_ODOMETRYM']._serialized_end=279
  _globals['_PUZZLEBOTODOMETRY']._serialized_start=281
  _globals['_PUZZLEBOTODOMETRY']._serialized_end=363
# @@protoc_insertion_point(module_scope)
